Add sent, open & click tracking
voiio/emark pull request #40
Opened 2023-06-25 13:22 UTC by codingjoe

2023-06-26 11:55 UTC, amureki requested changes
Awesome feature!

I have first comments here, but I still need to do the testing part.

2023-06-26 11:58 UTC, amureki requested changes
Also, as you mentioned - we need to think about rate limiting.

2023-07-06 15:24 UTC, codingjoe commented on README.md
> +not support HTML emails.
Why you hating my commas ;)

2023-07-07 08:15 UTC, amureki approved these changes
Shall we do a beta release first?

2023-07-17 13:38 UTC, amureki requested changes
I did some tests, found a couple of things. Also, tracking is questionable, we'd need to test how it works in comparison to the mailing systems like Brevo, as here are the results from my test:

- checking an email via gmail (no ad-blockers) in browser does not count as opening
- gmail on iOS also does not count at all
- Microsoft Windows 10 Mail does not count at all
- MacOS Mail.app open counts as 1 open (no matter how many times you will open it)

2023-07-20 08:44 UTC, amureki commented on emark/models.py
> +    redirect_url = models.URLField()
I managed to break this.
`URLField()` by default has max_length=200 but the link I had in my email is much longer:

<details>

```
status=500 method=GET path="/emark/c6f4b2f2-62f9-4b59-9c29-3b5100d48c6d/click?url=https%3A%2F%2Fvoiio-platfo-emark-trac-munpyq.herokuapp.com%2Faccounts%2Flogin%2FINq%3A%3A1qMP4r%3AZfeHkYAT9UsgjZ_mLo0gxIhQaQy3UfrJR3cpMBEcVgA%3Futm_source%3Dplatform%26utm_medium%3Demail%26utm_campaign%3DLOGIN_EMAIL%26next%3D%252Fdiscover%252F"


django.db.utils.DataError: value too long for type character varying(200)
```

</details>

2023-07-20 13:25 UTC, amureki approved these changes
@codingjoe switching to `<img>` worked, opens are tracked in gmail desktop, as well as in the other clients.

So, from my side this is good to go now!

2023-07-20 14:31 UTC, merged